### ISSUE TITLE
Sunklies flying kinda broke waaaa

### ISSUE THREAD

**Issue by SuhuDevMan** [GrayAnimates/Soulles-DX#16]
1. Some times sunkies are so big they either 
A. Cover Everything
or
B. Are way off screen

And some Times the sunkies cannot be seen in certain directions

My solution would be to have checks for these sunkies and either scale them or have them move in a certain way
Side note: I recommend a Debug function to where you can trigger specific Sunkies to fly across in a specific way to help with testing

Image of the sunkleys Funkily
![image](https://user-images.githubusercontent.com/96299374/201803184-b9eb58f6-d319-472a-8f2c-e1d69ed952a6.png)
![image](https://user-images.githubusercontent.com/96299374/201803271-725bd300-c5f2-4aea-8b8a-9e292c8a1c77.png)
![image](https://user-images.githubusercontent.com/96299374/201803489-47bfcdb3-892e-4334-b1b9-114d897bd1f5.png)
![image](https://user-images.githubusercontent.com/96299374/201803557-ebe651aa-e510-42a7-a036-ade14b1c68e7.png)
![image](https://user-images.githubusercontent.com/96299374/201803723-8cf1b7e3-a5be-4b9e-a113-bec9d55ea4e1.png)
![image](https://user-images.githubusercontent.com/96299374/201804045-3a35eea3-94de-45bc-824d-019d938ac62d.png)
![image](https://user-images.githubusercontent.com/96299374/201804136-3bdba14a-d66c-4683-9539-889259def939.png)
![image](https://user-images.githubusercontent.com/96299374/201804884-e47d81b7-e960-4864-8048-b092955e9476.png)
(MY SUNKY!!! he broke :( plz fix my baby) 
![image](https://user-images.githubusercontent.com/96299374/201804792-ef865240-973f-4d72-a3f4-fdc6f0edab7f.png)

I would try to fix this myself, but i's still learning .Hscript (Though I will say I'm REALLY good with .Lua)

BTW on downscroll, the "BF UWU" part makes the notes hard to see

-- Hope i'm still not being annoying, SuhuDev

**Comment by SuhuDevMan** [comment]
Lick counter gave up 💀 
![image](https://user-images.githubusercontent.com/96299374/201806574-d4d28724-d9f5-47f7-8b36-5067ab6b1740.png)

**Comment by GrayAnimates** [comment]
this is a feature hehaha
also i'll flip the bf uwu sprite on downscroll so itll be fixed
