### ISSUE TITLE
Another ice cube bug + prey

### ISSUE THREAD

**Issue by SuhuDevMan** [GrayAnimates/Soulles-DX#17]
For some reason, during one turn BF didn't move inwards to lick
![image](https://user-images.githubusercontent.com/96299374/201806830-c2b8a557-d7f6-4fd2-a4c8-cc48b77de4b7.png)

During prey on downscroll (Haven't Tested Up) I cannot See my notes unless I activate the debug
also how do I exit prey
![image](https://user-images.githubusercontent.com/96299374/201807767-64e4b945-e3b5-47ff-a1a2-d2875525625e.png)

for some reason the notes show up sometimes, but not all the time, though that might be my PC

**Comment by SuhuDevMan** [comment]
FINNALLY GONNA PLAY SOULLESS FOR THE FIRST TIME!!!

**Comment by Stilic** [comment]
the downscroll on prey already got fixed (see #11)
try to update your local copy first

**Comment by SuhuDevMan** [comment]
As said, somtimes they do so up on downscroll
I am on the latest version of both SDX and Yoshi Engine

**Comment by Stilic** [comment]
it doesn't happen for me
so you have a skill issue i guess

**Comment by GrayAnimates** [comment]
update it again

**Comment by ArdoDev-stupid** [comment]
can you close this
