### ISSUE TITLE
Sou l             l e s       shit

### ISSUE THREAD

**Issue by SuhuDevMan** [GrayAnimates/Soulles-DX#18]
So first off, Ya i'm on botplay i'm eating ice cream

ok so 1.
i can barley see the Txt on downscroll: 
![image](https://user-images.githubusercontent.com/96299374/201808909-d55b90c2-3aa8-4e68-adbc-8567f1297008.png)
2. sometimes the slash effect studders (I couldn't capture this)

**Comment by GrayAnimates** [comment]
im reworking the hud so this should be fixed with the new health bar soon !!!

**Comment by SuhuDevMan** [comment]
yoka

**Comment by Snoni** [comment]
poop haha

**Comment by ArdoDev-stupid** [comment]
it's better now i think now can you close this
