### ISSUE TITLE
wheres the bulidddd????pls god

### ISSUE THREAD

**Issue by Itzunknwn** [GrayAnimates/Soulles-DX#4]

**Comment by Goofgoof43** [comment]
The entire repo is the build bruh

**Comment by arceuss** [comment]
compile it

**Comment by Mati278** [comment]
> _No description provided._

1. first download yoshicrafter engine: https://github.com/YoshiCrafter29/YoshiCrafterEngine/releases
2. download everything from here
3. put it on the yce mods folder
4. done!!!1!!

**Comment by startastic987** [comment]
how do you download?

**Comment by GrayAnimates** [comment]
click the code button
