### ISSUE TITLE
Sorry for another but i found two icecube bugs

### ISSUE THREAD

**Issue by SuhuDevMan** [GrayAnimates/Soulles-DX#7]
1. The left note can also act as a way to lick along with the space bar
2. sometimes the couonter skips when licking
once it when from 126 to like 200 somthing

**Comment by SuhuDevMan** [comment]
oh and i got 922 licks on ice cube, turns out all notes can lick

**Comment by SuhuDevMan** [comment]
WAIT, after you press Space, ANY key on the keyboard can use to be licked

**Comment by GrayAnimates** [comment]
it was a lick doubler feature 
im scrapping it
