### ISSUE TITLE
Hi sorry if i'm getting annoying

### ISSUE THREAD

**Issue by SuhuDevMan** [GrayAnimates/Soulles-DX#9]
I found a put in Sunshine OG ( i still have yet to play anything else beside sunshine og, prey, and ice cube)
Tails in light out part is just a haxe fixil logo
![image](https://user-images.githubusercontent.com/96299374/201257610-727c9038-1639-4c60-af3e-a1ed41281e10.png)
BTW, small grivence but not bug, the txt is hard to see on downscroll

**Comment by SuhuDevMan** [comment]
YOU CAN LICK XENO??
![image](https://user-images.githubusercontent.com/96299374/201258956-0cdc6889-7fc5-470e-87d6-d731475d50fb.png)

**Comment by GrayAnimates** [comment]
use yoshi v2.3
